
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public TbHero TbHero {get; }
    public TbMonster TbMonster {get; }
    public TbSkill TbSkill {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbHero = new TbHero(loader("tbhero"));
        TbMonster = new TbMonster(loader("tbmonster"));
        TbSkill = new TbSkill(loader("tbskill"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbHero.ResolveRef(this);
        TbMonster.ResolveRef(this);
        TbSkill.ResolveRef(this);
    }
}

}
