
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbMonster
{
    private readonly System.Collections.Generic.Dictionary<int, TableMonster> _dataMap;
    private readonly System.Collections.Generic.List<TableMonster> _dataList;
    
    public TbMonster(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, TableMonster>(n);
        _dataList = new System.Collections.Generic.List<TableMonster>(n);
        for(int i = n ; i > 0 ; --i)
        {
            TableMonster _v;
            _v = global::cfg.TableMonster.DeserializeTableMonster(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TableMonster> DataMap => _dataMap;
    public System.Collections.Generic.List<TableMonster> DataList => _dataList;

    public TableMonster GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public TableMonster Get(int key) => _dataMap[key];
    public TableMonster this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

